### PR TITLE
Allow use of cache folder and custom gcode commands

### PR DESCRIPTION
**Pull request by Pavulon87**
With these changes, all commands from the terminal are transferred to the printer: e.g. Home(G28), Nozzle temp.(M104), Fan speed(M106) and work as expected.

Recently printed files (cache/ folder) are displayed in the file list and can be printed.

Tested on P1S. Maybe at least some of the code can be used.

### CODE REVIEW

**Comment by atax112** [comment]
Does this mean that also controling the printer would work from Octoprint? So far my A1 wont nudge when trying controls.

**Comment by Pavulon87** [comment]
@atax112 Standard gcode works, so octoprint control works as well. You can set the temperature or move the print head.

**Comment by jneilliii** [comment]
Yeah, my goal was to implement this in a future change after the core functionality was working well. That being said, based on some videos I've seen recently the ability to send general gcode may be blocked in the future.

**Comment by Pavulon87** [comment]
Understandable.  I hope they will leave at least the basic functions such as temperature or homing.

**Comment by jneilliii** [comment]
Curious, what's stored in cache folder, mine has always been empty.

**Comment by Pavulon87** [comment]
Every file that i print using a "print plate" from Bambu/Orca Slicer. In the main directory there are only "Send" files

Zrzut ekranu 2024-02-12 214235

**Comment by jneilliii** [comment]
Interesting, for the X1 both print and sent files all go into root. One other question about your PR. I noticed you re-enabled the M26 command with a S0 parameter. Just curious if that's part of the cancel process that might be breaking starting a new print after cancel? I had told @atax112 already that the firmware protocol settings for cancel command needs to be adjusted in OctoPrint to use M524 for cancel instead of the standard M25, as that's used for pause and cancel and needed to distinguish the two.

**Comment by jneilliii** [comment]
Never mind about the M26 question, I see that it is sent from OctoPrint on cancel.

**Comment by jneilliii** [comment]
had to add a little extra to it for dealing with empty cache folder, but the changes are not live with version 0.0.11.

**Comment by jneilliii** [comment]
looks like switching `print_job.get("subtask_name")` to `print_job.get("gcode_file")` has broken the plugin's ability to recognize a print started from the printer. going to have to revert that back. Not even sure why you changed that?

**Comment by Pavulon87** [comment]
> looks like switching `print_job.get("subtask_name")` to `print_job.get("gcode_file")` has broken the plugin's ability to recognize a print started from the printer. going to have to revert that back. Not even sure why you changed that?

@jneilliii This is a problem, because in my case it is the "subtask name" that breaks the plugin.

`"subtask_name":"cube_","gcode_file":"cube_.3mf"`
Without extension file is not recognized.

subtask_name:
Zrzut ekranu 2024-02-13 120733

gcode_file:
Zrzut ekranu 2024-02-13 120932

Maybe this is due to the difference between X1 and P1?

**Comment by jneilliii** [comment]
This might be one of those quirks with sending vs printing? Did this file happen to be a cube from orca's calibration menu? Did it do the same if you actually start new project and slice, etc. manually?

**Comment by Pavulon87** [comment]
No, it wasn't a calibration cube. Random file. Add primitive -> cube -> Slice plate -> Print plate
In each case, this is what it looks like using a "print plate":
`"subtask_name":"xxx","gcode_file":"xxx.3mf"`

When printing from octoprint:
`"subtask_name":"cache_xxx.3mf","gcode_file":"xxx.3mf"`

**Comment by jneilliii** [comment]
Ok, will adjust the code tonight, that appears to be a difference between x1 and p1.

**Comment by Pavulon87** [comment]
One more test. After sending the file via "Send" button and selecting it from the printer panel, I receive:
`"subtask_name":"xxx.gcode.3mf","gcode_file":"xxx.gcode.3mf"`
File "xxx.gcode.3mf" is located in root directory.

**Comment by jneilliii** [comment]
Yeah, so boils down to how the slicer is starting the job vs OctoPrint starting the job. The slicer is stripping that full name out for subtask name. I'll attempt your if 3mf in subtas_name approach tonight after work.

**Comment by jneilliii** [comment]
0.0.13 version out now with conditional change. if it's not working for you on the P1, please open an issue in the repo.

**Comment by jneilliii** [comment]
I think I figured out why prints go to cache vs root of the sd card. Seems that if your printer is cloud connected when you print it uploads it through the cloud vs straight to the device. Putting your Bambu in local only mode I believe would change the behavior you are seeing. I've personally only ran my in local only mode unless I was doing a firmware update, which is why my cache folder was empty. That being said, I manually uploaded a file into the folder with filezilla and it completely broke the file listing for me with loads of errors like this
```
2024-02-17 02:05:39,646 - pybambu - ERROR - Exception data: 550 Could not get file size.
```
I think I was able to fix it by changing to this block:
```
        for entry in filelistcache:
            if entry.startswith("/"):
                filename = entry[1:].replace("cache/", "")
            else:
                filename = entry.replace("cache/", "")
            filesize = ftp.ftps_session.size(entry)
            date_str = ftp.ftps_session.sendcmd(f"MDTM {entry}").replace("213 ", "")
            filedate = datetime.datetime.strptime(date_str, "%Y%m%d%H%M%S").replace(tzinfo=datetime.timezone.utc).timestamp()
            dosname = get_dos_filename(filename, existing_filenames=list(result.keys())).lower()
```

**Pull request merged**
